class PostDecorator < ApplicationDecorator
  decorates :post

  # Accessing Helpers
  #   You can access any helper via a proxy
  #
  #   Normal Usage: helpers.number_to_currency(2)
  #   Abbreviated : h.number_to_currency(2)
  #   
  #   Or, optionally enable "lazy helpers" by calling this method:
  #     lazy_helpers
  #   Then use the helpers with no proxy:
  #     number_to_currency(2)

  # Defining an Interface
  #   Control access to the wrapped subject's methods using one of the following:
  #
  #   To allow only the listed methods (whitelist):
  #     allows :method1, :method2
  #
  #   To allow everything except the listed methods (blacklist):
  #     denies :method1, :method2

  # Presentation Methods
  #   Define your own instance methods, even overriding accessors
  #   generated by ActiveRecord:
  #   
  #   def created_at
  #     h.content_tag :span, time.strftime("%a %m/%d/%y"), 
  #                   :class => 'timestamp'
  #   end
  
  def hash_tags
    model.tags.map {|tag| "##{tag.term}"}.join(", ")
  end
  
  def last_updated
    h.distance_of_time_in_words_to_now model.updated_at
  end
  
  def published_on
    h.time_tag model.publish_at, :pubdate => true, :format => '%B %d, %Y at %l:%M %p'
  end

end