production:
  adapter: mysql2
  encoding: utf8
  host: db.example.com
  port: 3306
  database: example_db
  username: example
  password: secret
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
